/**
 * Crowd Rush — crowd formation.
 *
 * A crowd of N runners is a set of *slots*: stable (ox, oz) offsets from the
 * crowd's centre, generated by a sunflower (golden-angle) distribution so the
 * pack reads as an organic blob, never a rigid grid. Slot 0 is dead centre and
 * near the front; higher indices spiral outward and backward.
 *
 * The distribution is scaled to fit the track: as N grows the pack gets a bit
 * wider and deeper but is clamped to the usable half-width so a 200-runner
 * crowd can still be steered between gates. When N shrinks, the highest-index
 * slots are the ones that leave — so the pack contracts from its edges.
 *
 * Slots are cached by N; runners lerp toward their slot every frame, which is
 * what makes growth and loss look smooth rather than teleporting.
 */

const GOLDEN = Math.PI * (3 - Math.sqrt(5));
const cache = new Map();

export function formationFor(n, halfWidth = 4.2) {
  const key = `${n}|${halfWidth.toFixed(2)}`;
  const hit = cache.get(key);
  if (hit) return hit;

  const slots = new Array(n);
  // pack density: ~0.55 units between neighbours, tightened as the crowd grows
  const spacing = n > 120 ? 0.42 : n > 50 ? 0.48 : 0.55;
  const maxR = Math.min(halfWidth, spacing * Math.sqrt(n) * 0.62);

  for (let i = 0; i < n; i++) {
    const frac = n === 1 ? 0 : i / (n - 1);
    const r = maxR * Math.sqrt(frac);
    const a = i * GOLDEN;
    let ox = Math.cos(a) * r;
    let oz = Math.sin(a) * r;
    // squash depth a little so the crowd is wider than it is long, and push it
    // back behind the leader (runners trail, they don't lead)
    oz = oz * 0.7 - r * 0.35 - 0.2;
    ox = Math.max(-halfWidth, Math.min(halfWidth, ox));
    slots[i] = { ox, oz, ring: r / (maxR || 1) };
  }

  const out = { slots, width: maxR, depth: maxR * 0.9 + 0.6 };
  if (cache.size > 200) cache.clear();
  cache.set(key, out);
  return out;
}

/** Half-width the crowd centre may occupy so its edge runners stay on-track. */
export function steerHalfWidth(trackHalf, crowdWidth) {
  return Math.max(0.4, trackHalf - crowdWidth * 0.6);
}
